language: python
python:
  - '3.5'
  - '3.8'
  - '3.9'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="_Projet8.settings"

services:
  - postgresql

script:
  - python3 manage.py test

